# -*- coding: utf-8 -*-
"""tree-decision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQi7Ek2gTwiRCHmRwmtkAOY8wPlCFd1H
"""

class Node:
    def __init__(self, question=None, yes=None, no=None, result=None):
        self.question = question
        self.yes = yes
        self.no = no
        self.result = result

def diagnosa(node):
    while node:
        if node.result is not None:
            print("\n")
            print(f"Rekomendasi Outfit: {node.result}")
            break
        jawab = input(f"{node.question} (ya/tidak): ").strip().lower()
        if jawab == 'ya':
            node = node.yes
        elif jawab == 'tidak':
            node = node.no
        else:
            print("Jawaban tidak valid. Harap masukkan 'ya' atau 'tidak'.")

def buat_tree():
    node_result_indoor_pagi = Node(result="""Outfit Indoor Pagi: Tank top, celana pendek, sepatu gym, dan headphone. Cocok untuk sesi pagi!

![Outfit Indoor Pagi](https://img.freepik.com/free-photo/front-view-man-standing-looking-away_23-2148605612.jpg?semt=ais_hybrid)
""")

    node_result_indoor_sore = Node(result="""Outfit Indoor Sore: Kaos longgar, celana training, sepatu gym, dan botol minum. Ideal untuk sore hari!
    ![Outfit Indoor Sore](https://img.freepik.com/free-photo/sporty-man-portrait-gray-background_158595-5961.jpg?semt=ais_hybrid)
""")

    node_result_outdoor_pagi = Node(result="""Outfit Outdoor Pagi: Kaos olahraga, celana pendek, sepatu lari, dan topi. Sempurna untuk pagi!
    ![Outfit Outdoor Pagi](https://img.freepik.com/free-photo/man-wearing-black-sunglasses-blue-shirt_181624-28419.jpg?ga=GA1.1.1302525377.1731054268&semt=ais_hybrid)
""")
    node_result_outdoor_sore = Node(result="""Outfit Outdoor Sore: Jaket ringan, celana panjang, sepatu trail, dan botol air. Cocok untuk di sore hari!
    ![Outfit Outdoor Sore](https://img.freepik.com/premium-photo/hiker-taking-food-break-shade-tree_79405-735.jpg?ga=GA1.1.1302525377.1731054268&semt=ais_hybrid)
""")

    node_result_visual_pagi = Node(result="""Outfit Visual Pagi: Kaos santai, celana jogger, dan sepatu sneakers. di pagi hari!
    ![Outfit Visual Pagi](https://img.freepik.com/free-photo/male-athlete-doing-fitness-training-workout-outside-gym_1328-4754.jpg?ga=GA1.1.1302525377.1731054268&semt=ais_hybrid)
""")
    node_result_visual_sore = Node(result="""Outfit Visual Sore: Kemeja kasual, celana panjang, dan sepatu kasual. Cocok untuk di sore hari.
    ![Outfit Visual Sore](https://img.freepik.com/free-photo/man-navy-blue-shirt-pants-casual-wear-fashion-full-body_53876-125244.jpg?ga=GA1.1.1302525377.1731054268&semt=ais_hybrid)
""")

    node_result_pertunjukan_pagi = Node(result="""Outfit Pertunjukan Pagi: Kaos polos, celana panjang, dan sepatu loafers. Cocok untuk di pagi hari!
    ![Outfit Pertunjukan Pagi](https://img.freepik.com/free-photo/handsome-man-exiting-subway_23-2147932469.jpg?ga=GA1.1.1302525377.1731054268&semt=ais_hybrid)
""")
    node_result_pertunjukan_sore = Node(result="""Outfit Pertunjukan Sore: Blazer santai, celana chino, dan sepatu formal. Ideal untuk sore.
    ![Outfit Pertunjukan Sore](https://img.freepik.com/free-photo/handsome-man-exiting-subway_23-2147932469.jpg?ga=GA1.1.1302525377.1731054268&semt=ais_hybrid)
""")

    node_waktu_indoor = Node("Apakah Anda beraktivitas di Pagi?", yes=node_result_indoor_pagi, no=node_result_indoor_sore)
    node_waktu_outdoor = Node("Apakah Anda beraktivitas di Pagi?", yes=node_result_outdoor_pagi, no=node_result_outdoor_sore)

    node_waktu_visual = Node("Apakah Anda beraktivitas di Pagi?", yes=node_result_visual_pagi, no=node_result_visual_sore)
    node_waktu_pertunjukan = Node("Apakah Anda beraktivitas di Pagi?", yes=node_result_pertunjukan_pagi, no=node_result_pertunjukan_sore)

    node_gym = Node("Apakah Anda pemula di Gym?", yes=node_waktu_indoor, no=node_waktu_indoor)
    node_yoga = Node("Apakah Anda pemula di Yoga?", yes=node_waktu_indoor, no=node_waktu_indoor)

    node_lari = Node("Apakah Anda pemula di Lari?", yes=node_waktu_outdoor, no=node_waktu_outdoor)
    node_hiking = Node("Apakah Anda pemula di Hiking?", yes=node_waktu_outdoor, no=node_waktu_outdoor)

    node_lukis = Node("Apakah Anda pemula di Lukis?", yes=node_waktu_visual, no=node_waktu_visual)
    node_foto = Node("Apakah Anda pemula di Fotografi?", yes=node_waktu_visual, no=node_waktu_visual)

    node_musik = Node("Apakah Anda pemula di Musik?", yes=node_waktu_pertunjukan, no=node_waktu_pertunjukan)
    node_tari = Node("Apakah Anda pemula di Tari?", yes=node_waktu_pertunjukan, no=node_waktu_pertunjukan)

    node_indoor = Node("Apakah Anda lebih suka Gym?", yes=node_gym, no=node_yoga)
    node_outdoor = Node("Apakah Anda lebih suka Lari?", yes=node_lari, no=node_hiking)

    node_visual = Node("Apakah Anda lebih suka Melukis?", yes=node_lukis, no=node_foto)
    node_pertunjukan = Node("Apakah Anda lebih suka Musik?", yes=node_musik, no=node_tari)

    node_olahraga = Node("Apakah Anda suka olahraga indoor?", yes=node_indoor, no=node_outdoor)
    node_seni = Node("Apakah Anda suka seni visual?", yes=node_visual, no=node_pertunjukan)

    root = Node("Hobimu olahraga?", yes=node_olahraga, no=node_seni)

    return root

if __name__ == "__main__":
    tree = buat_tree()
    diagnosa(tree)